/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ExamSys.frontend;

import com.ExamSys.backend.Exam;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;

/**
 *
 * @author zhuan
 */
public class ExamsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ExamListJPanel
     */
    public ExamsJPanel() {
        initComponents();
        
        this.reload();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListExams = new javax.swing.JList<>();
        examJPanel = new com.ExamSys.frontend.ExamJPanel();

        setName("Exams"); // NOI18N

        jListExams.setMaximumSize(new java.awt.Dimension(200, 0));
        jListExams.setMinimumSize(new java.awt.Dimension(200, 80));
        jListExams.setName(""); // NOI18N
        jListExams.setPreferredSize(new java.awt.Dimension(200, 80));
        jListExams.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListExamsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListExams);

        jSplitPane1.setLeftComponent(jScrollPane1);
        jSplitPane1.setRightComponent(examJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jListExamsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListExamsValueChanged
        // TODO add your handling code here:
        if (!evt.getValueIsAdjusting()) {
            int idx=this.jListExams.getSelectedIndex();
            if (idx>=0) {
                Exam exam=(Exam)this.exams.get(idx);
                this.examJPanel.setExam(exam);
            }
        }
    }//GEN-LAST:event_jListExamsValueChanged

    public void reload() {
        DefaultListModel examListModel=new DefaultListModel();
        this.exams=Exam.getAllExams();
        
        for (int i=0;i<this.exams.size();i++)
            examListModel.addElement(this.exams.get(i));
        this.jListExams.setModel(examListModel);
        this.examJPanel.setExam(null);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.ExamSys.frontend.ExamJPanel examJPanel;
    private javax.swing.JList<String> jListExams;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
    List<Exam> exams=null;
}
