/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ExamSys.frontend;

/**
 *
 * @author zhuan
 */
public class ExamJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ExamJFrame
     */
    public ExamJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chooseExamJPanel = new com.ExamSys.frontend.ChooseExamJPanel();
        examWizardJPanel = new com.ExamSys.frontend.ExamWizardJPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());
        getContentPane().add(chooseExamJPanel, "SelectExam");
        getContentPane().add(examWizardJPanel, "ExamWizard");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.ExamSys.frontend.ChooseExamJPanel chooseExamJPanel;
    private com.ExamSys.frontend.ExamWizardJPanel examWizardJPanel;
    // End of variables declaration//GEN-END:variables

    void reload() {
        this.chooseExamJPanel.reload();
    }
}
