/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ExamSys.frontend;

import com.ExamSys.backend.Problem;
import com.ExamSys.backend.ProblemSection;
import java.awt.Dialog;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author zhuan
 */
public class ProblemJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProblemJPanel
     */
    public ProblemJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonUpdateProblem = new javax.swing.JButton();
        jButtonDeleteProblem = new javax.swing.JButton();
        jButtonNewProblem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListSections = new javax.swing.JList<>();
        jButtonNewSection = new javax.swing.JButton();
        jButtonDeleteSection = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxAnswer = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();

        jButtonUpdateProblem.setText("Update");
        jButtonUpdateProblem.setEnabled(false);
        jButtonUpdateProblem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateProblemActionPerformed(evt);
            }
        });

        jButtonDeleteProblem.setText("Delete");
        jButtonDeleteProblem.setEnabled(false);
        jButtonDeleteProblem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteProblemActionPerformed(evt);
            }
        });

        jButtonNewProblem.setText("New");
        jButtonNewProblem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewProblemActionPerformed(evt);
            }
        });

        jListSections.setEnabled(false);
        jScrollPane1.setViewportView(jListSections);

        jButtonNewSection.setText("New Section");
        jButtonNewSection.setEnabled(false);
        jButtonNewSection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewSectionActionPerformed(evt);
            }
        });

        jButtonDeleteSection.setText("Delete Section");
        jButtonDeleteSection.setEnabled(false);
        jButtonDeleteSection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteSectionActionPerformed(evt);
            }
        });

        jLabel1.setText("ID ");

        jTextFieldId.setToolTipText("");
        jTextFieldId.setEnabled(false);

        jLabel2.setText("Answer");

        jComboBoxAnswer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));
        jComboBoxAnswer.setEnabled(false);

        jLabel3.setText("Name");

        jTextFieldName.setToolTipText("");
        jTextFieldName.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldName))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonUpdateProblem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonDeleteProblem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonNewProblem))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonNewSection)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonDeleteSection))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUpdateProblem)
                    .addComponent(jButtonDeleteProblem)
                    .addComponent(jButtonNewProblem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNewSection)
                    .addComponent(jButtonDeleteSection))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNewProblemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewProblemActionPerformed
        // TODO add your handling code here:
        this.clear();
        this.setReadonly(false);
        this.jButtonUpdateProblem.setEnabled(true);
        this.jButtonDeleteProblem.setEnabled(false);
        this.jButtonUpdateProblem.setText("Add");
    }//GEN-LAST:event_jButtonNewProblemActionPerformed

    private void jButtonNewSectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewSectionActionPerformed
        // TODO add your handling code here:
        String section=JOptionPane.showInputDialog(jScrollPane1, "Input Text");
        ((DefaultListModel)this.jListSections.getModel()).addElement(section);
        this.problem=null;
    }//GEN-LAST:event_jButtonNewSectionActionPerformed

    private void jButtonDeleteSectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteSectionActionPerformed
        // TODO add your handling code here:
        int idx=this.jListSections.getSelectedIndex();
        if (idx>=0) {
            ((DefaultListModel)this.jListSections.getModel()).remove(idx);
        }
    }//GEN-LAST:event_jButtonDeleteSectionActionPerformed

    private void jButtonUpdateProblemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateProblemActionPerformed
        // TODO add your handling code here:
        if (this.jTextFieldName.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Name cannot be blank", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } 
        Problem p;
        if (this.problem!=null) p=this.problem;
        else p=new Problem();
        p.setName(this.jTextFieldName.getText());
        p.setAnswer((char)(this.jComboBoxAnswer.getSelectedIndex()+'A'));
        ListModel model=this.jListSections.getModel();
        p.getSections().clear();
        for (int i=0;i<model.getSize();i++) {
            ProblemSection ps=new ProblemSection();
            ps.setText((String)model.getElementAt(i));
            p.getSections().add(ps);
        }
        if (this.problem!=null) {
            p.update();
        } else {
            p.create();
        }
        ((ProblemsJPanel)this.getParent().getParent()).reload();
    }//GEN-LAST:event_jButtonUpdateProblemActionPerformed

    private void jButtonDeleteProblemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteProblemActionPerformed
        // TODO add your handling code here:
        if (this.problem!=null) {
            this.problem.remove();
            ((ProblemsJPanel)this.getParent().getParent()).reload();
        }
    }//GEN-LAST:event_jButtonDeleteProblemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDeleteProblem;
    private javax.swing.JButton jButtonDeleteSection;
    private javax.swing.JButton jButtonNewProblem;
    private javax.swing.JButton jButtonNewSection;
    private javax.swing.JButton jButtonUpdateProblem;
    private javax.swing.JComboBox<String> jComboBoxAnswer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jListSections;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables
    private Problem problem;

    
    void setProblem(Problem p) {
        this.problem=p;
        if (p==null) return;
        this.jTextFieldId.setText(""+this.problem.getID());
        this.jComboBoxAnswer.setSelectedIndex(this.problem.getAnswer()-'A');
        this.jTextFieldName.setText(this.problem.getName());
        DefaultListModel listModel=new DefaultListModel();
        for (ProblemSection section:this.problem.getSections()) {
            listModel.addElement(section.getText());
        }
        this.jListSections.setModel(listModel);
        this.setReadonly(false);
        this.jButtonUpdateProblem.setText("Update");
        this.jButtonUpdateProblem.setEnabled(true);
    }

    public void setReadonly(boolean b) {
        this.jTextFieldId.setEnabled(false);
        this.jTextFieldName.setEnabled(!b);
        this.jComboBoxAnswer.setEnabled(!b);
        this.jListSections.setEnabled(!b);
        this.jButtonNewProblem.setEnabled(true);
        this.jButtonDeleteProblem.setEnabled(!b);
        this.jButtonUpdateProblem.setEnabled(false);
        this.jButtonDeleteSection.setEnabled(!b);
        this.jButtonNewSection.setEnabled(!b);
    }

    void clear() {
        
        this.jTextFieldId.setText("");
        this.jTextFieldName.setText("");
        this.jComboBoxAnswer.setSelectedIndex(0);
        DefaultListModel model=new DefaultListModel();
        this.jListSections.setModel(model);
    }
}
