/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ExamSys.frontend;

import com.ExamSys.backend.Problem;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 * The view for edit with a left list contains all problems to select and a right pane to edit the selected problem.
 * @author yang
 */
public final class ProblemsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProblemsJPanel
     */
    public ProblemsJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListProblems = new javax.swing.JList<>();
        problemJPanel = new com.ExamSys.frontend.ProblemJPanel();

        jListProblems.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListProblemsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListProblems);

        jSplitPane1.setLeftComponent(jScrollPane1);
        jSplitPane1.setRightComponent(problemJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * The event handler when a problem in the left list is selected.
     * @param evt The event object.
     */
    private void jListProblemsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListProblemsValueChanged
        // TODO add your handling code here:
        int idx=this.jListProblems.getSelectedIndex();
        if (idx>=0) {
            Problem problem=this.problems.get(idx);
            this.problemJPanel.setProblem(problem);
        }
    }//GEN-LAST:event_jListProblemsValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> jListProblems;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private com.ExamSys.frontend.ProblemJPanel problemJPanel;
    // End of variables declaration//GEN-END:variables

    private List<Problem> problems=null;
    
    /**
     * Reload the left problem list and clear the right problem info page.
     */
    public void reload() {
        DefaultListModel listModel=new DefaultListModel();
        this.problems=Problem.getAllProblems();
        
        for (int i=0;i<this.problems.size();i++)
            listModel.add(i, this.problems.get(i));
        this.jListProblems.setModel(listModel);
        
        this.problemJPanel.clear();
        this.problemJPanel.setReadonly(true);
        this.problemJPanel.setProblem(null);
    }
}
