/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ExamSys.frontend;

import com.ExamSys.backend.ProblemScore;
import com.ExamSys.backend.Report;
import java.util.List;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author zhuan
 */
public class ReportJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReportJPanel
     */
    public ReportJPanel() {
        initComponents();
        this.jTextFieldScore.setHorizontalAlignment(JTextField.RIGHT);
        
        DefaultTableModel model=new DefaultTableModel();
        model.addColumn("Problem");
        model.addColumn("Answer");
        model.addColumn("Your Aws");
        model.addColumn("Score");
        this.jTableDetails.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldStudent = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldExam = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldScore = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDetails = new javax.swing.JTable();

        jLabel1.setText("Student");

        jTextFieldStudent.setEnabled(false);

        jLabel2.setText("Exam");

        jTextFieldExam.setToolTipText("");
        jTextFieldExam.setEnabled(false);

        jLabel3.setText("Score");

        jTextFieldScore.setEnabled(false);

        jLabel4.setText("Details");

        jTableDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Problem", "Answer", "Your Ans", "Score"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableDetails);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldStudent, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addComponent(jTextFieldExam)
                    .addComponent(jTextFieldScore, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldExam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableDetails;
    private javax.swing.JTextField jTextFieldExam;
    private javax.swing.JTextField jTextFieldScore;
    private javax.swing.JTextField jTextFieldStudent;
    // End of variables declaration//GEN-END:variables

    private Report report=null;
    void setReport(Report rep) {
        if (rep==null) {
            this.report=null;
            this.clear();
        } else {
            this.report=rep;
            this.jTextFieldStudent.setText(report.getStudent().toString());
            this.jTextFieldExam.setText(report.getExam().toString());
            this.jTextFieldScore.setText(""+report.getScore());
            
            List<ProblemScore> problems=this.report.getExam().getProblems();
            
            DefaultTableModel model=(DefaultTableModel)this.jTableDetails.getModel();
            model.setRowCount(0);
            for (int i=0;i<problems.size();i++) {
                ProblemScore ps=problems.get(i);
                int[] sa=this.report.getScoreList().get(i);
                Object[] row= new Object[] {ps.getProblem().toString(),
                        ps.getProblem().getAnswer(),
                        (char)sa[1],
                        sa[0]
                };
                model.addRow(row);
            }
        }
    }

    private void clear() {
        this.jTextFieldExam.setText("");
        this.jTextFieldScore.setText("");
        this.jTextFieldStudent.setText("");
        DefaultTableModel model = (DefaultTableModel)this.jTableDetails.getModel();
        model.setRowCount(0);
    }
}
