/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ExamSys.frontend;

import com.ExamSys.backend.Report;
import com.ExamSys.backend.User;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 * The view to view all reports with a left list contains all reports for user to select 
 * and the right pane contains the view to show the selected report.
 * @author yang
 */
public class ReportsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReportsJPanel
     */
    public ReportsJPanel() {
        initComponents();
        this.jSplitPane1.setResizeWeight(1.0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListReports = new javax.swing.JList<>();
        reportJPanel = new com.ExamSys.frontend.ReportJPanel();

        jListReports.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListReports.setMinimumSize(new java.awt.Dimension(200, 0));
        jListReports.setPreferredSize(new java.awt.Dimension(200, 0));
        jListReports.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListReportsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListReports);

        jSplitPane1.setLeftComponent(jScrollPane1);
        jSplitPane1.setRightComponent(reportJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jListReportsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListReportsValueChanged
        // TODO add your handling code here:
        if (!evt.getValueIsAdjusting()) {
            int idx=this.jListReports.getSelectedIndex();
            if (idx>=0) {
                Report report=this.reports.get(idx);
                this.reportJPanel.setReport(report);
            }
        }
    }//GEN-LAST:event_jListReportsValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> jListReports;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private com.ExamSys.frontend.ReportJPanel reportJPanel;
    // End of variables declaration//GEN-END:variables

    private List<Report> reports=null;
    
    /**
     * Relate a student user to this view. 
     * It will read all the reports of this student and fill the left list.
     * @param student The Student object.
     */
    void setStudent(User student) {
        if (student==null) {
            if (this.reports!=null) {
                this.reports=null;
                this.clear();
            }
            
        }
        else {
            
            this.reports=Report.getReportsByStudentName(student.getUserName());
            DefaultListModel model=new DefaultListModel();
            for (Report report:this.reports) {
                model.addElement(report);
            }
            this.jListReports.setModel(model);
            this.reportJPanel.setReport(null);
        }
    }

    /**
     * Clear the current view and its sub views.
     */
    public void clear() {
        ((DefaultListModel)this.jListReports.getModel()).clear();
        this.reportJPanel.setReport(null);
    }
}
