/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ExamSys.frontend;

/**
 * The dialog window for a student to take an exam.
 * @author yang
 */
public class TakeExamJDialog extends javax.swing.JDialog {

    /**
     * Creates new form TakeExamJDialog
     */
    public TakeExamJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chooseExamJPanel = new com.ExamSys.frontend.ChooseExamJPanel();
        examWizardJPanel = new com.ExamSys.frontend.ExamWizardJPanel();
        reportJPanel = new com.ExamSys.frontend.ReportJPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());
        getContentPane().add(chooseExamJPanel, "ChooseExam");
        getContentPane().add(examWizardJPanel, "ExamWizard");
        getContentPane().add(reportJPanel, "Report");

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.ExamSys.frontend.ChooseExamJPanel chooseExamJPanel;
    private com.ExamSys.frontend.ExamWizardJPanel examWizardJPanel;
    private com.ExamSys.frontend.ReportJPanel reportJPanel;
    // End of variables declaration//GEN-END:variables

    /**
     * Reload all contents for the dialog view.
     */
    void reload() {
        this.chooseExamJPanel.reload();
    }
}
